/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pd3_26.midterm_project;

/**
 *
 * @author DELL
 */
public class OrderObj extends javax.swing.JFrame {

    /**
     * Creates new form OrderObj
     */
    public OrderObj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WebcamUsedMax = new javax.swing.JLabel();
        SoftWUsedMax = new javax.swing.JLabel();
        HeadPUsedMax = new javax.swing.JLabel();
        MaskUsedMax = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LaptopUsedMax = new javax.swing.JLabel();
        MiceUsedMax = new javax.swing.JLabel();
        MicsUsedMax = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LaptopNo = new javax.swing.JTextField();
        LaptopNo1 = new javax.swing.JTextField();
        LaptopNo2 = new javax.swing.JTextField();
        LaptopNo3 = new javax.swing.JTextField();
        LaptopNo4 = new javax.swing.JTextField();
        LaptopNo5 = new javax.swing.JTextField();
        LaptopNo6 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        StaplerBoxUsedMax = new javax.swing.JLabel();
        PensUsedMax = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MarkersUsedMax = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        BoardMarkUsedMax = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        NoteBUsedMax = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        StickyNUsedMax = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        StaplerUsedMax = new javax.swing.JLabel();
        LaptopNo7 = new javax.swing.JTextField();
        LaptopNo8 = new javax.swing.JTextField();
        LaptopNo9 = new javax.swing.JTextField();
        LaptopNo10 = new javax.swing.JTextField();
        LaptopNo11 = new javax.swing.JTextField();
        LaptopNo12 = new javax.swing.JTextField();
        LaptopNo13 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Objects");

        WebcamUsedMax.setText("used/max");

        SoftWUsedMax.setText("used/max");

        HeadPUsedMax.setText("used/max");

        MaskUsedMax.setText("used/max");

        jLabel2.setText("Laptops:");

        jLabel3.setText("Computer Mice:");

        jLabel4.setText("Computer Mics:");

        jLabel5.setText("Webcams:");

        jLabel6.setText("Software Kit:");

        jLabel7.setText("Headphones:");

        jLabel8.setText("Face Masks:");

        LaptopUsedMax.setText("used/max");

        MiceUsedMax.setText("used/max");

        MicsUsedMax.setText("used/max");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Objects in Use:");

        LaptopNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNoActionPerformed(evt);
            }
        });

        LaptopNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo1ActionPerformed(evt);
            }
        });

        LaptopNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo2ActionPerformed(evt);
            }
        });

        LaptopNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo3ActionPerformed(evt);
            }
        });

        LaptopNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo4ActionPerformed(evt);
            }
        });

        LaptopNo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo5ActionPerformed(evt);
            }
        });

        LaptopNo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo6ActionPerformed(evt);
            }
        });

        jLabel32.setText("Stapler Boxes:");

        jLabel13.setText("Pen Pairs:");

        StaplerBoxUsedMax.setText("used/max");

        PensUsedMax.setText("used/max");

        jLabel18.setText("Marker Pairs:");

        MarkersUsedMax.setText("used/max");

        jLabel20.setText("Board Marker Pairs:");

        BoardMarkUsedMax.setText("used/max");

        jLabel22.setText("Notebooks:");

        NoteBUsedMax.setText("used/max");

        jLabel28.setText("Sticky Notes:");

        StickyNUsedMax.setText("used/max");

        jLabel30.setText("Staplers:");

        StaplerUsedMax.setText("used/max");

        LaptopNo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo7ActionPerformed(evt);
            }
        });

        LaptopNo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo8ActionPerformed(evt);
            }
        });

        LaptopNo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo9ActionPerformed(evt);
            }
        });

        LaptopNo10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo10ActionPerformed(evt);
            }
        });

        LaptopNo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo11ActionPerformed(evt);
            }
        });

        LaptopNo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo12ActionPerformed(evt);
            }
        });

        LaptopNo13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaptopNo13ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setText("Number of Required Objects");

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Order Selected");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LaptopNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaptopNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaptopNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(HeadPUsedMax)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SoftWUsedMax))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(WebcamUsedMax)
                                                    .addComponent(MicsUsedMax)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                                .addComponent(MiceUsedMax))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LaptopUsedMax))))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LaptopNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaptopNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaptopNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MaskUsedMax)
                                .addGap(18, 18, 18)
                                .addComponent(LaptopNo6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(StickyNUsedMax)
                                        .addGap(18, 18, 18)
                                        .addComponent(LaptopNo11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NoteBUsedMax)
                                        .addGap(18, 18, 18)
                                        .addComponent(LaptopNo10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BoardMarkUsedMax)
                                        .addGap(18, 18, 18)
                                        .addComponent(LaptopNo9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MarkersUsedMax)
                                        .addGap(18, 18, 18)
                                        .addComponent(LaptopNo8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PensUsedMax)
                                        .addGap(18, 18, 18)
                                        .addComponent(LaptopNo7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StaplerUsedMax))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StaplerBoxUsedMax)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LaptopNo12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LaptopNo13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LaptopUsedMax)
                            .addComponent(LaptopNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(PensUsedMax)
                            .addComponent(LaptopNo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(MiceUsedMax)
                            .addComponent(LaptopNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(MarkersUsedMax)
                            .addComponent(LaptopNo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MicsUsedMax)
                            .addComponent(LaptopNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel20)
                            .addComponent(BoardMarkUsedMax)
                            .addComponent(LaptopNo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WebcamUsedMax)
                            .addComponent(LaptopNo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel22)
                            .addComponent(NoteBUsedMax)
                            .addComponent(LaptopNo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SoftWUsedMax)
                            .addComponent(LaptopNo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel28)
                            .addComponent(StickyNUsedMax)
                            .addComponent(LaptopNo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HeadPUsedMax)
                            .addComponent(LaptopNo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel30)
                            .addComponent(StaplerUsedMax)
                            .addComponent(LaptopNo12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaskUsedMax)
                            .addComponent(LaptopNo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel32)
                            .addComponent(StaplerBoxUsedMax)
                            .addComponent(LaptopNo13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LaptopNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNoActionPerformed

    private void LaptopNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo1ActionPerformed

    private void LaptopNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo2ActionPerformed

    private void LaptopNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo3ActionPerformed

    private void LaptopNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo4ActionPerformed

    private void LaptopNo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo5ActionPerformed

    private void LaptopNo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo6ActionPerformed

    private void LaptopNo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo7ActionPerformed

    private void LaptopNo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo8ActionPerformed

    private void LaptopNo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo9ActionPerformed

    private void LaptopNo10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo10ActionPerformed

    private void LaptopNo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo11ActionPerformed

    private void LaptopNo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo12ActionPerformed

    private void LaptopNo13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaptopNo13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaptopNo13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderObj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderObj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderObj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderObj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderObj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoardMarkUsedMax;
    private javax.swing.JLabel HeadPUsedMax;
    private javax.swing.JTextField LaptopNo;
    private javax.swing.JTextField LaptopNo1;
    private javax.swing.JTextField LaptopNo10;
    private javax.swing.JTextField LaptopNo11;
    private javax.swing.JTextField LaptopNo12;
    private javax.swing.JTextField LaptopNo13;
    private javax.swing.JTextField LaptopNo2;
    private javax.swing.JTextField LaptopNo3;
    private javax.swing.JTextField LaptopNo4;
    private javax.swing.JTextField LaptopNo5;
    private javax.swing.JTextField LaptopNo6;
    private javax.swing.JTextField LaptopNo7;
    private javax.swing.JTextField LaptopNo8;
    private javax.swing.JTextField LaptopNo9;
    private javax.swing.JLabel LaptopUsedMax;
    private javax.swing.JLabel MarkersUsedMax;
    private javax.swing.JLabel MaskUsedMax;
    private javax.swing.JLabel MiceUsedMax;
    private javax.swing.JLabel MicsUsedMax;
    private javax.swing.JLabel NoteBUsedMax;
    private javax.swing.JLabel PensUsedMax;
    private javax.swing.JLabel SoftWUsedMax;
    private javax.swing.JLabel StaplerBoxUsedMax;
    private javax.swing.JLabel StaplerUsedMax;
    private javax.swing.JLabel StickyNUsedMax;
    private javax.swing.JLabel WebcamUsedMax;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
