/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pd3_26.midterm_project;

/**
 *
 * @author DELL
 */
public class ManagerMenu extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMenu
     */
    public ManagerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LaptopUsedMax = new javax.swing.JLabel();
        MiceUsedMax = new javax.swing.JLabel();
        MicsUsedMax = new javax.swing.JLabel();
        WebcamUsedMax = new javax.swing.JLabel();
        SoftWUsedMax = new javax.swing.JLabel();
        HeadPUsedMax = new javax.swing.JLabel();
        MaskUsedMax = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PensUsedMax = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MarkersUsedMax = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        BoardMarkUsedMax = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        NoteBUsedMax = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        StickyNUsedMax = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        StaplerUsedMax = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        StaplerBoxUsedMax = new javax.swing.JLabel();
        LogOutBut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        EmployeeMenu = new javax.swing.JMenu();
        NewEmployeeBut = new javax.swing.JMenu();
        AccessExistingEmpBut = new javax.swing.JMenu();
        SupplyMenu = new javax.swing.JMenu();
        RequestSeeBut = new javax.swing.JMenu();
        OrderBut = new javax.swing.JMenu();

        jLabel24.setText("Pen Pairs:");

        jLabel25.setText("used/max");

        jLabel26.setText("Pen Pairs:");

        jLabel27.setText("used/max");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMS - Manager Menu");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Objects in use:");

        jLabel2.setText("Laptops:");

        jLabel3.setText("Computer Mice:");

        jLabel4.setText("Computer Mics:");

        jLabel5.setText("Webcams:");

        jLabel6.setText("Software Kit:");

        jLabel7.setText("Headphones:");

        jLabel8.setText("Face Masks:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        LaptopUsedMax.setText("used/max");

        MiceUsedMax.setText("used/max");

        MicsUsedMax.setText("used/max");

        WebcamUsedMax.setText("used/max");

        SoftWUsedMax.setText("used/max");

        HeadPUsedMax.setText("used/max");

        MaskUsedMax.setText("used/max");

        jLabel13.setText("Pen Pairs:");

        PensUsedMax.setText("used/max");

        jLabel18.setText("Marker Pairs:");

        MarkersUsedMax.setText("used/max");

        jLabel20.setText("Board Marker Pairs:");

        BoardMarkUsedMax.setText("used/max");

        jLabel22.setText("Notebooks:");

        NoteBUsedMax.setText("used/max");

        jLabel28.setText("Sticky Notes:");

        StickyNUsedMax.setText("used/max");

        jLabel30.setText("Staplers:");

        StaplerUsedMax.setText("used/max");

        jLabel32.setText("Stapler Boxes:");

        StaplerBoxUsedMax.setText("used/max");

        LogOutBut.setText("Log out");
        LogOutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButActionPerformed(evt);
            }
        });

        EmployeeMenu.setText("Employee");

        NewEmployeeBut.setText("Register New Employee");
        NewEmployeeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewEmployeeButMouseClicked(evt);
            }
        });
        EmployeeMenu.add(NewEmployeeBut);

        AccessExistingEmpBut.setText("Access Existing Employees");
        AccessExistingEmpBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccessExistingEmpButMouseClicked(evt);
            }
        });
        EmployeeMenu.add(AccessExistingEmpBut);

        jMenuBar1.add(EmployeeMenu);

        SupplyMenu.setText("Supply");

        RequestSeeBut.setText("View Requests");
        RequestSeeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RequestSeeButMouseClicked(evt);
            }
        });
        SupplyMenu.add(RequestSeeBut);

        OrderBut.setText("Order Objects");
        OrderBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderButMouseClicked(evt);
            }
        });
        SupplyMenu.add(OrderBut);

        jMenuBar1.add(SupplyMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MaskUsedMax)
                                    .addComponent(HeadPUsedMax)
                                    .addComponent(SoftWUsedMax)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(WebcamUsedMax)
                                    .addComponent(MicsUsedMax)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(MiceUsedMax))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LaptopUsedMax)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PensUsedMax))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MarkersUsedMax))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(BoardMarkUsedMax))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NoteBUsedMax))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StickyNUsedMax))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StaplerUsedMax))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StaplerBoxUsedMax)))))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogOutBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(PensUsedMax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(MarkersUsedMax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(BoardMarkUsedMax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(NoteBUsedMax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(StickyNUsedMax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(StaplerUsedMax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(StaplerBoxUsedMax)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LaptopUsedMax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(MiceUsedMax))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MicsUsedMax)
                                .addGap(18, 18, 18)
                                .addComponent(WebcamUsedMax)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SoftWUsedMax)
                                .addGap(18, 18, 18)
                                .addComponent(HeadPUsedMax)
                                .addGap(18, 18, 18)
                                .addComponent(MaskUsedMax)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOutBut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ChooseAccountType ChAT = new ChooseAccountType();
        ChAT.setVisible(true);
    }//GEN-LAST:event_LogOutButActionPerformed

    private void AccessExistingEmpButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccessExistingEmpButMouseClicked
        // TODO add your handling code here:
        EmployeeAccess EmpAcc = new EmployeeAccess(); 
        EmpAcc.setVisible(true);
    }//GEN-LAST:event_AccessExistingEmpButMouseClicked

    private void NewEmployeeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewEmployeeButMouseClicked
        // TODO add your handling code here:
        EmployeeRegistration EmpReg = new EmployeeRegistration();
        EmpReg.setVisible(true);
    }//GEN-LAST:event_NewEmployeeButMouseClicked

    private void RequestSeeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestSeeButMouseClicked
        // TODO add your handling code here:
        EmpReq ER = new EmpReq();
        ER.setVisible(true);
    }//GEN-LAST:event_RequestSeeButMouseClicked

    private void OrderButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderButMouseClicked
        // TODO add your handling code here:
        OrderObj OO = new OrderObj();
        OO.setVisible(true);
    }//GEN-LAST:event_OrderButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccessExistingEmpBut;
    private javax.swing.JLabel BoardMarkUsedMax;
    private javax.swing.JMenu EmployeeMenu;
    private javax.swing.JLabel HeadPUsedMax;
    private javax.swing.JLabel LaptopUsedMax;
    private javax.swing.JButton LogOutBut;
    private javax.swing.JLabel MarkersUsedMax;
    private javax.swing.JLabel MaskUsedMax;
    private javax.swing.JLabel MiceUsedMax;
    private javax.swing.JLabel MicsUsedMax;
    private javax.swing.JMenu NewEmployeeBut;
    private javax.swing.JLabel NoteBUsedMax;
    private javax.swing.JMenu OrderBut;
    private javax.swing.JLabel PensUsedMax;
    private javax.swing.JMenu RequestSeeBut;
    private javax.swing.JLabel SoftWUsedMax;
    private javax.swing.JLabel StaplerBoxUsedMax;
    private javax.swing.JLabel StaplerUsedMax;
    private javax.swing.JLabel StickyNUsedMax;
    private javax.swing.JMenu SupplyMenu;
    private javax.swing.JLabel WebcamUsedMax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
